/* index — embedded retrieval engine, C ABI.
 *
 * ONE ABI serves every target. The same sixty-one symbols are exported by the wasm32 artifact
 * (browser, Node, edge worker) and by the native cdylib (`.dll` / `.so` / `.dylib`), because the
 * binding is hand-written rather than generated by wasm-bindgen. Any language with a C FFI —
 * Python ctypes, Go cgo, Java FFM, C#, Ruby, PHP, Zig, or C itself — binds against this file.
 *
 * Build the native library:
 *     cargo build -p index-wasm --release
 *         -> target/release/index_wasm.dll     (Windows)
 *         -> target/release/libindex_wasm.so   (Linux)
 *         -> target/release/libindex_wasm.dylib (macOS)
 *
 * MEMORY MODEL — and the one place native and wasm differ.
 *
 *   Native hosts own their own memory and pass their own pointers straight in. Every function that
 *   takes `(ptr, len)` reads it within the call and retains nothing, so a stack buffer, a Python
 *   `bytes`, or a Go slice is fine. `idx_alloc` / `idx_free` exist for WASM hosts, which cannot
 *   hand a pointer into the module's linear memory any other way; native hosts may ignore them.
 *
 *   WASM hosts must additionally re-read the memory buffer after every `idx_alloc`: allocation can
 *   call `memory.grow()`, which detaches every existing view.
 *
 * ERROR MODEL — nothing traps.
 *
 *   A trap kills the whole WASM instance, so no input can cause one. Bad pointers, malformed bytes
 *   and invalid UTF-8 all return a sentinel: NULL for pointer returns, 0 for counts, and
 *   UINT32_MAX for `idx_search` and `idx_build_add`. Note that a WASM host reading an i32 sees
 *   UINT32_MAX as -1 unless it coerces; that is a real bug this project shipped once.
 *
 * THREADING. A handle is not synchronised. `idx_search` takes `*mut` because it writes the result
 * buffer into the handle, so one handle serves one thread at a time. Separate handles over separate
 * byte buffers are independent and need no locking.
 */

#ifndef INDEX_H
#define INDEX_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque. Created by idx_open or idx_build_finish, destroyed by idx_close. */
typedef struct IdxHandle IdxHandle;

/* Opaque. Created by idx_build_new; consumed by idx_build_finish OR released by idx_build_free —
 * exactly one of the two, never both. */
typedef struct IdxBuilder IdxBuilder;

/* The wire separator for field specs and document field values. A literal NUL byte. */
#define IDX_FIELD_SEPARATOR '\0'

/* Bytes per hit in the result buffer: doc (uint32), score (float), typo_bucket (uint32),
 * all little-endian, tightly packed. */
#define IDX_HIT_BYTE 12

/* ABI version. Bump on any breaking change to these signatures. Currently 12 (the image tier:
 * twelve idx_image_* symbols, an embedding that crosses as raw float rather than as JSON, and a
 * per-hit `why` bitmask so a fused answer stays explicable across the boundary).
 *
 * NOTE the serialized FORMAT version moves independently of this, and is now IDXTEXT7: the
 * section table grew two spans for token positions (6) and one for document keys (7). An older
 * reader mis-parses the wider table as posting data and produces plausible garbage rather than an
 * error, which is why the magic changes with it. An index written by an older build will not open
 * in this one -- rebuild it. */
uint32_t idx_abi_version(void);

/* ---- Memory, for WASM hosts only ---------------------------------------------------------- */
uint8_t *idx_alloc(size_t len);
void idx_free(uint8_t *ptr, size_t len);

/* ---- Building ------------------------------------------------------------------------------ */

/* Create a builder from a NUL-separated list of "name:boost:b" triples,
 * e.g. "name:3:0.4\0brand:1:0.6". `boost` weights the field; `b` is the BM25 length-normalisation
 * parameter for it. Returns NULL on a malformed spec, an empty spec, or too many fields. */
IdxBuilder *idx_build_new(const uint8_t *ptr, size_t len);

/* Add one document: a NUL-separated list of field values, positionally aligned with the schema.
 * Returns the document ordinal, or UINT32_MAX on error. */
uint32_t idx_build_add(IdxBuilder *b, const uint8_t *ptr, size_t len);

/* Designate field `field` as a stored FACET before adding any document: a value kept verbatim
 * per document, for filtering and counting rather than scoring. Returns 1 on success, 0 if the
 * builder is null or the field is out of range.
 *
 * Facet values are deliberately NOT tokenized -- "Lucky Me" is one value, not two terms. Values are
 * interned, so the cost is the field's cardinality plus one uint32 per document.
 *
 * Call once per field to facet on. Call order is SLOT order: the first call is slot 0, and the
 * query functions below take that slot, not the schema field index. A repeated field is ignored
 * rather than duplicated. Returns 0 if any document has already been added. */
uint32_t idx_build_facet(IdxBuilder *b, uint32_t field);

/* Designate field `field` as a NUMERIC column before adding any document, for range filtering
 * and histograms. Returns 1 on success, 0 if the builder is null, the field is out of range, or
 * a document has already been added. Slot order is call order, independent of facet slots.
 *
 * Values are parsed once as double. Text that does not parse as a finite number becomes NaN,
 * which no range contains -- an absent value is excluded from every filter rather than treated
 * as zero. Doubles, not floats: a float carries 24 bits of mantissa, so a price in minor units
 * stops being exact above about 16.7 million. */
uint32_t idx_build_numeric(IdxBuilder *b, uint32_t field);

/* Record token positions, for idx_search_phrase. Returns 1 on success, 0 if the builder is null or
 * a document has already been added -- positions cannot be recovered afterwards, because the
 * analyzed tokens are not kept.
 *
 * Opt-in, and it is the only build option whose cost scales with token OCCURRENCES rather than
 * with documents: one uint32 per occurrence, against eight bytes per (term, document) pair for the
 * postings themselves. Short product names roughly double; prose does much worse. An index that
 * answers no phrase query stores nothing. */
uint32_t idx_build_position(IdxBuilder *b);

/* Finish building. CONSUMES the builder — do not use it again, and do not call idx_build_free on
 * it afterwards. Returns NULL if the build fails. */
IdxHandle *idx_build_finish(IdxBuilder *b);

/* Discard a builder that will never be finished. */
void idx_build_free(IdxBuilder *b);

/* ---- Loading and saving -------------------------------------------------------------------- */

/* Parse a serialized index. The bytes are copied into owned structures, so the caller may free its
 * buffer as soon as this returns. Returns NULL on malformed input rather than trapping. */
IdxHandle *idx_open(const uint8_t *ptr, size_t len);

/* Serialize a live index into the handle's result buffer. Returns the byte length, or 0 on error;
 * read the bytes with idx_result_ptr. Lets a host build once and cache the bytes. */
size_t idx_serialize(IdxHandle *h);

void idx_close(IdxHandle *h);

/* ---- Querying ------------------------------------------------------------------------------ */

uint32_t idx_doc_count(const IdxHandle *h);
uint32_t idx_term_count(const IdxHandle *h);

/* Search for up to `k` hits. `prefix` non-zero runs a prefix (typeahead) query instead of a whole
 * word one. Returns the hit count, or UINT32_MAX on error. Read the hits with idx_result_ptr:
 * `count * IDX_HIT_BYTE` bytes. Typo correction is always on; `typo_bucket` in each hit is the
 * edit-distance cost, and hits are ordered by that FIRST and score second. */
uint32_t idx_search(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k, uint32_t prefix);

/* ---- Faceting ------------------------------------------------------------------------------ */

/* idx_search restricted to documents whose facet value is exactly the UTF-8 string at `v`/`v_len`.
 * Filter-then-rank: asking for `k` hits in a rare category returns `k` if `k` exist, rather than
 * however many survive a global top-`k`. An unknown value returns 0, not everything.
 * Hits are written to the result buffer in the usual IDX_HIT_BYTE format. */
uint32_t idx_search_facet(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k, uint32_t slot,
                          const uint8_t *v, size_t v_len);

/* Conjunctive faceted search: every `slot=value` pair in the NUL-separated `spec` must hold, e.g.
 * "0=Colgate " "1=Accessory". The slot is decimal; the value is everything after the FIRST `=`,
 * so a value may itself contain `=`.
 *
 * This is what a storefront asks -- brand AND category -- and it is one pass, not an intersection
 * of separate result sets. Returns UINT32_MAX on a malformed spec, and 0 when the filter is
 * unsatisfiable. Never everything: that is the dangerous reading of a filter. */
uint32_t idx_search_facet_all(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k,
                              const uint8_t *spec, size_t spec_len);

/* Count how many documents matching `q` carry each value of facet `slot`, over EVERY match --
 * not the top `k`. That is the only count a shopper can act on: "Snacks (412)" has to mean 412
 * results exist, not 412 within a page.
 *
 * Writes into the result buffer, one entry after another, little-endian and unpadded:
 *
 *     uint32 label_len; uint8 label[label_len]; uint32 count;
 *
 * Length-prefixed rather than NUL-separated, because a facet value may legitimately contain
 * anything except a NUL and this encoding need not assume even that. Returns the entry count, or
 * UINT32_MAX on error. Sorted by count descending, then value ascending. */
uint32_t idx_facet_tally(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t slot);

/* ---- Numeric ranges ------------------------------------------------------------------------ */

/* idx_search restricted to `lo <= value < hi` on numeric column `slot`.
 *
 * Half-open on purpose: adjacent buckets in a price filter must not both contain the boundary,
 * or the counts beside them add up to more than the result set. An unknown slot returns 0. */
uint32_t idx_search_range(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k,
                          uint32_t slot, double lo, double hi);

/* Histogram of numeric column `slot` over EVERY document matching `q`.
 *
 * `edge`/`edge_n` are ascending bucket boundaries; bucket i is edge[i] <= v < edge[i+1].
 * Writes `edge_n - 1` little-endian uint32 counts into the result buffer and returns that
 * number, or UINT32_MAX on error. A document with no value in the column is counted in no
 * bucket, so the counts sum to AT MOST the match count rather than exactly it. */
uint32_t idx_range_tally(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t slot,
                         const double *edge, size_t edge_n);

/* Sort matching documents by numeric column `slot` instead of by relevance: "price, low to
 * high". `ascending` non-zero gives smallest first. Documents with no value are excluded --
 * there is no position in a price order for a product with no price.
 *
 * THIS CANNOT PRUNE. Relevance ordering is what lets the engine stop early; a numeric order
 * gives it nothing to stop on, because the cheapest item may match the query worst. Cost tracks
 * the query's match count, not k. `score` and `typo_bucket` in each hit are still populated
 * honestly, so a host can show relevance beside a price sort; they just do not order it. */
uint32_t idx_search_sorted(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k,
                           uint32_t slot, uint32_t ascending);

/* How many numeric columns the index carries. */
uint32_t idx_numeric_slot_count(const IdxHandle *h);

/* Number of distinct values in facet `slot`. 0 when the slot does not exist. */
uint32_t idx_facet_count(const IdxHandle *h, uint32_t slot);

/* How many facet slots the index carries. 0 when it has no facet field. */
uint32_t idx_facet_slot_count(const IdxHandle *h);

/* Pointer to the last result written for this handle, by idx_search or idx_serialize.
 * INVALIDATED by the next idx_search or idx_serialize on the same handle — copy before reusing. */
const uint8_t *idx_result_ptr(const IdxHandle *h);
size_t idx_result_len(const IdxHandle *h);

/* The full filter bar, with paging: OR within a clause, AND across clauses, NOT, and an offset.
 *
 * `spec` is a NUL-separated list of clauses, each `slot[!]=v1|v2|...`:
 *     "0=Colgate|Oral B"   slot 0 is Colgate OR Oral B
 *     "1!=discontinued"    slot 1 is NOT discontinued
 *
 * Clauses are AND-ed. `|` separates alternatives, so a facet value containing `|` cannot be
 * expressed; every other byte can, including `=` after the first one.
 *
 * An unknown value is ignored. An include whose values are ALL unknown matches nothing; an exclude
 * whose values are all unknown excludes nothing. Returns UINT32_MAX on a malformed spec and 0 when
 * unsatisfiable -- never everything. */
uint32_t idx_search_clause(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t k,
                           uint32_t offset, const uint8_t *spec, size_t spec_len);

/* idx_search starting at `offset` -- page n is offset = n * k.
 *
 * COST GROWS WITH OFFSET, not k: the engine over-fetches offset + k and drops the prefix, because
 * rank order is only known once everything above the page is scored. For deep paging, filter. */
uint32_t idx_search_page(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t offset, uint32_t k);

/* Phrase query: the query's tokens, consecutive and in order, within ONE field. `offset` pages it.
 *
 * Requires an index built with idx_build_position. WITHOUT positions this returns 0 hits and does
 * NOT fall back to an ordinary term search -- a fallback would return bag-of-words rows that are
 * indistinguishable from phrase rows once they are in the buffer.
 *
 * A phrase is EXACT: no token is typo-corrected or prefix-expanded, because quoting is the caller
 * asserting these words. A token absent from the dictionary matches nothing, which is the same
 * direction as an include clause whose values are all unknown.
 *
 * Ranking is unchanged. The phrase is a filter applied after scoring, like a facet clause, so a
 * phrase hit carries the score the same query would have given it. */
uint32_t idx_search_phrase(IdxHandle *h, const uint8_t *q, size_t q_len, uint32_t offset,
                           uint32_t k);

/* ---- Highlighting --------------------------------------------------------------------------- */

/* Byte ranges of `text` that matched `q` -- what a UI bolds.
 *
 * The index does not store field text, so the caller passes back the row it already has. That is
 * the right shape for an embedded engine: the application owns the rows, and a second copy kept
 * only to highlight them is the duplication this engine exists to avoid.
 *
 * Writes `count` pairs of little-endian uint32 (start, end) into the result buffer and returns
 * `count`, or UINT32_MAX on a bad pointer or invalid UTF-8. Ranges are ascending, non-overlapping,
 * and always land on UTF-8 character boundaries.
 *
 * Spans come from the SAME analysis the index used, so a typo-corrected hit highlights the real
 * word: querying "Colgte" marks "Colgate". */
uint32_t idx_highlight(IdxHandle *h, const uint8_t *q, size_t q_len,
                       const uint8_t *text, size_t text_len);

/* ---- Incremental updates: a live, appendable collection ------------------------------------- */

/* An ordered set of immutable segments, searched as one. This is the incremental-update path:
 * building a corpus is O(corpus), but adding today's new rows should not be, so new rows go into a
 * small segment that is cheap to build and every query merges across segments.
 *
 * Compaction is a REBUILD from the application's own rows, not a merge of segments -- the rows
 * belong to the app, and rebuilding from them is both simpler and more correct than merging
 * per-segment statistics. `idx_searcher_needs_compaction` says when it is worth doing. */
typedef struct IdxSearcher IdxSearcher;

/* CONSUMES the handle. Do not use or close it afterwards. */
IdxSearcher *idx_searcher_new(IdxHandle *h);

/* CONSUMES the handle. Returns 1 on success. Existing document ordinals stay valid -- the new
 * segment's documents take the NEXT global ordinals, so an id handed out earlier still resolves. */
uint32_t idx_searcher_push(IdxSearcher *s, IdxHandle *h);

void idx_searcher_close(IdxSearcher *s);

uint32_t idx_searcher_doc_count(const IdxSearcher *s);
uint32_t idx_searcher_segment_count(const IdxSearcher *s);
uint32_t idx_searcher_live_count(const IdxSearcher *s);

/* Non-zero when too much of the collection lives outside the largest segment, or too much is
 * deleted. Rebuild from source rows when this turns on. */
uint32_t idx_searcher_needs_compaction(const IdxSearcher *s);

/* Tombstone by GLOBAL ordinal. Returns 1 if it was live. */
uint32_t idx_searcher_delete(IdxSearcher *s, uint32_t global);

/* All of these write to the SEARCHER's own result buffer -- read it with
 * idx_searcher_result_ptr / _len, not the per-handle ones. Hits use global ordinals. */
uint32_t idx_searcher_search(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t k,
                             uint32_t prefix);
uint32_t idx_searcher_search_facet_all(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t k,
                                       const uint8_t *spec, size_t spec_len);
uint32_t idx_searcher_search_range(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t k,
                                   uint32_t slot, double lo, double hi);
uint32_t idx_searcher_search_sorted(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t k,
                                    uint32_t slot, uint32_t ascending);

/* The full filter bar across every segment: `spec` is the same slot[!]=v1|v2|... grammar
 * idx_search_clause takes, and is parsed by the same code, so one spec cannot mean two things.
 *
 * The unknown-value rule applies PER SEGMENT: a value one segment has never interned is ignored
 * there, so an include whose values are all unknown to a segment draws nothing from it, and an
 * exclude whose values are all unknown removes nothing from it. That is what lets a filter bar
 * built from one segment's labels stay correct against a searcher holding several. Reversing the
 * two is how a filter silently returns the whole corpus. */
uint32_t idx_searcher_search_clause(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t k,
                                    uint32_t offset, const uint8_t *spec, size_t spec_len);

/* idx_searcher_search from `offset` -- page n is offset = n * k.
 *
 * Cost grows with `offset` AND with segment count together, not with k: every segment must produce
 * offset + k hits before the merge can decide which of them the page holds, because the page
 * boundary is global -- a segment's 3rd-best hit can be the page's 1st. For deep paging, filter. */
uint32_t idx_searcher_search_page(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t offset,
                                  uint32_t k);

/* idx_search_phrase across every segment. A segment built without positions contributes nothing,
 * rather than contributing term matches that would be unidentifiable after the merge. */
uint32_t idx_searcher_search_phrase(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t offset,
                                    uint32_t k);

/* Facet tally across every segment, merged by VALUE rather than by interned id -- two segments
 * intern their labels independently, so the same integer means different things in each. Same
 * length-prefixed encoding as idx_facet_tally. */
uint32_t idx_searcher_facet_tally(IdxSearcher *s, const uint8_t *q, size_t q_len, uint32_t slot);

const uint8_t *idx_searcher_result_ptr(const IdxSearcher *s);
size_t idx_searcher_result_len(const IdxSearcher *s);

/* ---- The image tier: pixels and captions in ONE index --------------------------------------- */

/* An image IS a document here. That is the whole architectural bet, and it is why these functions
 * sit in this header rather than in a second one: a caption is a scored text field, a camera model
 * is a facet, a capture year is a numeric column, an embedding is a vector column, and a perceptual
 * hash is a hash column -- five column types over ONE document set, answered by ONE query plan that
 * selects top-k exactly ONCE.
 *
 * Every FOSS incumbent (Immich, LibrePhotos, PhotoPrism) needs a server to answer a question about
 * your own files, and each of them splits the vector store from the relational row and intersects
 * the two in application code. That intersection is where their result pages get short: a document
 * ranked 51st by text and 51st by vector, with k = 50, is plausibly the best FUSED result and both
 * arms discarded it before the intersection ran. Nothing at the intersection layer can recover it.
 *
 * An image tier callable only from Rust would forfeit that argument exactly where it matters most,
 * because the browser is where the incumbents fail. Hence: same ABI, same header, same idioms.
 *
 * Opaque. Created by idx_image_new, made searchable by idx_image_build, destroyed by
 * idx_image_free. ONE handle covers both lifetimes -- a separate builder object would be one more
 * thing for a host with no destructors to leak, and this way the ordering rule is enforced by the
 * sentinels rather than by documentation: queries refuse before the build, mutations refuse after
 * it. */
typedef struct IdxImage IdxImage;

/* Bytes per image hit: doc (uint32), score (float), why (uint32), little-endian and packed.
 *
 * The same width as IDX_HIT_BYTE, with `why` in the slot `typo_bucket` occupies for a text hit, so
 * a host that already decodes text hits renames one field rather than writing a second decoder. */
#define IDX_IMAGE_HIT_BYTE 12

/* Bytes per near-duplicate record from idx_image_hash_near: doc (uint32), distance (uint32). */
#define IDX_IMAGE_NEAR_BYTE 8

/* `why` bits -- which signal found a hit. A fused answer is only worth having if it is explicable:
 * "matched your caption AND looks like your reference" is a materially stronger result than either
 * alone, and the caller is entitled to know which it got. IDX_WHY_COLOR is reserved: no arm sets it
 * yet, and defining the bit now means adding one later is not an ABI break. */
#define IDX_WHY_TEXT   1u
#define IDX_WHY_VECTOR 2u
#define IDX_WHY_HASH   4u
#define IDX_WHY_COLOR  8u

/* Metric codes for idx_image_new. Every metric is reported HIGHER IS BETTER -- L2 comes back as
 * the negated squared distance -- so one k-selection ranks them all and a fused plan never has to
 * special-case a distance. */
#define IDX_METRIC_COSINE 0u
#define IDX_METRIC_DOT    1u
#define IDX_METRIC_L2     2u

/* Create an image index builder.
 *
 * `ptr`/`len` is a NUL-separated field spec. Each field is "name:boost:b", exactly the grammar
 * idx_build_new takes, with ONE optional fourth component declaring the column type:
 *
 *     "caption:3:0.4"     a scored text field
 *     "camera:1:0.6:f"    also a FACET
 *     "year:0:0.6:n"      also a NUMERIC column
 *
 * Facet and numeric slots are numbered in field order. Declaring the column type inside the spec,
 * rather than through separate idx_image_facet / idx_image_numeric calls, is deliberate: on the
 * text side those calls must precede the first document and silently return 0 afterwards, which is
 * an ordering rule a host can get wrong and then ship. Here the schema is one argument and cannot
 * be half-applied. An unrecognised type letter is refused rather than ignored -- silently dropping
 * an `f` the caller typed as `F` would build an index whose filter bar matches nothing.
 *
 * `dim` is the embedding width, or 0 for a corpus with no embeddings at all. Such an index is still
 * fully searchable by text, facet, range and hash, and that is the point: embedding a corpus takes
 * hours (rclip: 15 hours for 84,725 images on a weak CPU), so "searchable now, semantically
 * searchable later" is the NORMAL state of an image index, not a transient one.
 *
 * Returns NULL on a malformed or empty spec, too many fields, or an unknown metric. */
IdxImage *idx_image_new(const uint8_t *ptr, size_t len, size_t dim, uint32_t metric);

/* Stage the embedding that the NEXT idx_image_add will attach.
 *
 * `ptr` points at `len` FLOATS in linear memory -- not bytes, not JSON.
 *
 * THE EMBEDDING NEVER CROSSES AS JSON, and this is a measured decision rather than a taste. A 512-d
 * float embedding is 2 KB raw and roughly 6 KB as JSON text that must then be PARSED on arrival.
 * At the ingest rates this tier is built for -- rclip managed 1.28 M images in 3 hours -- the
 * serialise/parse pair, not the search, would dominate the cost of the boundary, and it would buy
 * nothing: both sides already agree on IEEE-754 little-endian, so the copy is the whole conversion.
 * The host allocates with idx_alloc, writes floats at that offset, and passes the pointer, exactly
 * as idx_range_tally already takes its double edges.
 *
 * The corollary is a real constraint and is stated rather than hidden. An mmap-style format does
 * not FAIL to port to WASM; it silently reads the whole index into linear memory, and a vector
 * column is the largest thing this engine has ever put there. A 32-bit address space caps linear
 * memory at 4 GiB, so the corpus ceiling in a browser is set by (documents x dim x bytes-per-vector)
 * long before it is set by the postings. `js/image-smoke.mjs` reports the high-water mark for that
 * reason; a host indexing at scale should read it before assuming the browser will hold the corpus.
 *
 * Returns 1 on success, 0 on a null handle, a null pointer, a zero length, an index already built,
 * a column created with dim = 0, a length disagreeing with `dim`, or a non-finite component. The
 * dimension mismatch is refused HERE, at the call that can name both numbers, rather than surfacing
 * later as a failed add -- in a real ingest that mismatch means a model was swapped mid-run, and
 * the operator needs telling.
 *
 * Staging rather than taking a document ordinal keeps the pair atomic: an ordinal parameter would
 * let a host attach an embedding to a document that does not exist yet. */
uint32_t idx_image_push_vector(IdxImage *h, const float *ptr, size_t len);

/* Add one image: its text fields, its perceptual hashes, and its content digest.
 *
 * `ptr`/`len` is a NUL-separated list of field values positionally aligned with the schema -- the
 * same wire form idx_build_add takes.
 *
 * A 64-bit hash crosses as TWO uint32 HALVES rather than as one uint64, because a WASM i64 surfaces
 * in JavaScript as a BigInt: a second numeric type in the host's hot ingest loop, for a value that
 * is a bit pattern rather than a number. `present` says which hashes are real -- bit 0 dhash, bit 1
 * phash. An absent hash is genuinely absent, not zero: a zero hash is a legitimate all-dark image,
 * and conflating the two would make every unhashed document a near-duplicate of every other.
 *
 * `digest`/`digest_len` is the SHA-256 of the ORIGINAL bytes, the dedup key and the proof that a
 * 1:1 restore is 1:1. NULL means "not computed" and stores the zero digest; a non-NULL pointer
 * whose length is not exactly 32 is an error, because a truncated digest that compares equal to
 * nothing is worse than no digest at all.
 *
 * Any embedding staged by idx_image_push_vector is consumed here whether or not this call succeeds,
 * so a staged vector never leaks into the following document.
 *
 * Returns the document ordinal, or UINT32_MAX on any error. */
uint32_t idx_image_add(IdxImage *h, const uint8_t *ptr, size_t len, uint32_t present,
                       uint32_t dhash_hi, uint32_t dhash_lo,
                       uint32_t phash_hi, uint32_t phash_lo,
                       const uint8_t *digest, size_t digest_len);

/* Finish building. Returns 1 on success, 0 on a null handle, an already-built index, or a build
 * failure. The handle survives either way, so there is nothing extra to free on the error path. */
uint32_t idx_image_build(IdxImage *h);

/* Documents in a BUILT image index. 0 for a null handle or one still under construction. */
uint32_t idx_image_doc_count(const IdxImage *h);

/* Vector search alone: binary popcount shortlist, int8 rerank, exact final pass.
 *
 * `ptr`/`len` is the query embedding as `len` floats. `oversample` is the shortlist multiplier; 0
 * is treated as 1, and 4 is the measured recommendation -- a 3-4x oversampled rerank over binary
 * codes recovered recall to 0.98-0.9966 on OpenAI embeddings, and more than that buys shortlist the
 * rerank then throws away. It is a real parameter rather than a fixed default because a caller
 * trading recall against latency has nowhere else to turn the dial.
 *
 * Writes IDX_IMAGE_HIT_BYTE records with why = IDX_WHY_VECTOR and returns the count, or UINT32_MAX
 * on a null handle, an index not yet built, a null pointer, or a length disagreeing with `dim`.
 *
 * THIS APPLIES NO FILTER, and that is exactly why it is a separate entry point from
 * idx_image_search_fused: a host wanting a filtered vector search has to ask for one, so the filter
 * cannot be lost by accident. A vector arm quietly returning documents the filter bar excluded is
 * the defect this tier exists to not have. */
uint32_t idx_image_search_vector(IdxImage *h, const float *ptr, size_t len, uint32_t k,
                                 uint32_t oversample);

/* THE FUSED QUERY. Text, facets, numeric ranges, vector proximity and perceptual-hash proximity,
 * scored together, top-k selected ONCE.
 *
 * The claim is not speed, it is two correctness properties a fan-out architecture cannot have:
 *
 *   HARD PREDICATES ARE HARD EVERYWHERE. Facet and range clauses are applied inside the text pass
 *   AND re-applied to the vector and hash arms. A soft arm knows nothing about facets, so it must
 *   be filtered rather than trusted; skipping that step is precisely how a vector search leaks a
 *   document the filter bar excluded.
 *
 *   NO SHORT PAGE. Each soft arm over-generates candidates before fusion, so a document just
 *   outside every arm's own top-k is still reachable.
 *
 * Every predicate is optional, and a query with none of them is a legitimate match-everything --
 * social platforms strip EXIF from essentially every downloadable image, so a corpus where most
 * documents carry almost no signal is the normal case rather than the exception.
 *
 *   q, q_len          Free text, BM25F. NULL or 0 drops the text arm.
 *   spec, spec_len    The slot[!]=v1|v2|... filter-bar grammar idx_search_clause takes, parsed by
 *                     the SAME code, so one spec cannot mean two things. A malformed spec returns
 *                     UINT32_MAX -- never a silent match-everything.
 *   range, range_n    `range_n` TRIPLES of double laid out as slot, lo, hi; half-open lo <= v < hi.
 *                     The slot is a double too, so the array is one homogeneous buffer a host fills
 *                     with a single Float64Array; a whole number below 2^53 is exact. A slot that
 *                     is not a non-negative whole number is refused rather than truncated into some
 *                     other column's range.
 *   vec, vec_len      Query embedding as floats. A length disagreeing with `dim` is an ERROR, not
 *                     a silently dropped arm.
 *   hash_present,     A dHash probe and its Hamming radius. The radius is the caller's because a
 *   hash_hi/lo,       threshold measured for a 64-bit code does not port to a 256-bit one; 4 is the
 *   hash_max          measured default for this width.
 *   alpha             Weight of the text arm; the soft arms share the remainder. NEGATIVE means
 *                     "use the default", which is 0.5 and asserts nothing about which signal is
 *                     better -- the honest position before a labelled judgment set exists.
 *
 * Writes IDX_IMAGE_HIT_BYTE records and returns the count, or UINT32_MAX on error. Ties break by
 * agreement count and then by ascending ordinal, so the ranking is deterministic. */
uint32_t idx_image_search_fused(IdxImage *h, const uint8_t *q, size_t q_len,
                                const uint8_t *spec, size_t spec_len,
                                const double *range, size_t range_n,
                                const float *vec, size_t vec_len,
                                uint32_t hash_present, uint32_t hash_hi, uint32_t hash_lo,
                                uint32_t hash_max, float alpha, uint32_t k);

/* Near-duplicates of a dHash probe within a Hamming radius, over the whole hash column.
 *
 * The probe crosses as two uint32 halves, for the reason idx_image_add gives. Writes
 * IDX_IMAGE_NEAR_BYTE records -- doc, distance -- ordered by ascending distance then ascending
 * ordinal, and returns the count, or UINT32_MAX on a null handle or an index not yet built. A
 * document with no dHash appears in no result at all.
 *
 * This writes to the SAME buffer the searches use, in a DIFFERENT record layout. The count this
 * returns is what tells a host which decoder to run; read it before the next call. */
uint32_t idx_image_hash_near(IdxImage *h, uint32_t hi, uint32_t lo, uint32_t max);

/* Which signal found hit `hit` of the last search: a bitmask of IDX_WHY_*.
 *
 * Returns UINT32_MAX past the end of the last result or on a null handle -- never 0, which is a
 * legitimate mask meaning "no arm claimed it" and must stay distinguishable from an error.
 *
 * The mask is also the third field of every hit record, so a host decoding records itself never
 * needs this call. It exists for the host that wants one number about one row without writing a
 * decoder -- a Python or PHP binding, typically, where unpacking a packed struct is the fiddliest
 * part of the whole ABI. Explicability has to survive the boundary, or the fused plan's main
 * advantage over a fan-out stops being visible to the application. */
uint32_t idx_image_why(const IdxImage *h, uint32_t hit);

/* Image results live in the IMAGE handle's own buffer, not the text one. Invalidated by the next
 * call on the same handle. */
const uint8_t *idx_image_result_ptr(const IdxImage *h);
size_t idx_image_result_len(const IdxImage *h);

/* Release an image handle, built or not. Nothing else frees it. */
void idx_image_free(IdxImage *h);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* INDEX_H */
